### ISSUE TITLE
Matching color scheme?

### ISSUE THREAD

**Issue by D3SOX** [GabePoel/KvLibadwaita#1]
Great work on the theme but it doesn't fit with the color schemes I tried (Breeze Dark, Colloid Dark)
Which KDE color scheme do you use in combination with it?

**Comment by daudix** [comment]
@D3SOX This theme is designed to fit GNOME Libadwaita style

**Comment by D3SOX** [comment]
> @D3SOX This theme is designed to fit GNOME Libadwaita style

I know? I'm asking for a KDE color scheme because the theme doesn't provide one.

**Comment by daudix** [comment]
There is no color scheme, because it not designed for KDE

**Comment by D3SOX** [comment]
What KDE color scheme is used in the screenshot of Okular from the README then?

**Comment by daudix** [comment]
Okular from readme is installed on GNOME and themed using Kvantum, this theme not realted to KDE Plasma

**Comment by daudix** [comment]
If you want theme for KDE that looks pretty, check this one: [Colloid KDE](https://github.com/vinceliuice/Colloid-kde)

**Comment by eylles** [comment]
colorizing is possible, tho rn not pretty and jank, also not really documented and depends on pywal16 (at least at the moment of writing)

https://github.com/eylles/pywal16-libadwaita

**Comment by namesarebloat** [comment]
To answer the actual question, just in case someone's still looking for this, kvantum includes a colour scheme called KvGnomeDark, which is at least a good point to start

**Comment by queenbiscuit311** [comment]
> To answer the actual question, just in case someone's still looking for this, kvantum includes a colour scheme called KvGnomeDark, which is at least a good point to start

I've been using this color scheme and I can't really tell the difference between it and normal libadwaita apps, so i would deem it "close enough". I'm sure it could be tweaked a bit though.

**Comment by GabePoel** [comment]
Color schemes have been added with the latest commit. (Although they're not currently included in the install script.)
