### ISSUE TITLE
Improving the tab appearance

### ISSUE THREAD

**Issue by sith-on-mars** [GabePoel/KvLibadwaita#3]
Currently, the tab looks like this:
![image](https://user-images.githubusercontent.com/37974764/170868488-648c14ec-fe47-4115-9094-f455baf4c169.png)

Whereas the tab in Libadwaita looks like this:
![image](https://user-images.githubusercontent.com/37974764/170868577-4d749bc2-ce24-4ba3-b0c5-83782df1b1f4.png)

Would you consider to make the tab look more like in Libadwaita? Thank you!

**Comment by GabePoel** [comment]
Tabs have been redone in the latest version. They should match now.
