### ISSUE TITLE
[LineEdit] frame is grey for some reason 

### ISSUE THREAD

**Issue by Nereithr** [GabePoel/KvLibadwaita#4]
Title.  The frame for LineEdit (potentially other elements too) is, for some reason, grey,  [Here is a picture for reference.](https://i.imgur.com/WYIuDIi.png) The light theme works fine. -style=kvantum/-style=kvantum-dark make no difference.  I cannot find any issue with the dark SVG that would cause  this. Object names are the same between both light and dark themes and the the theme reacts accordingly by removing the LineEdit frame if the LineEdit elements are missing, renamed or made fully transparent. It's just the colour that doesn't work for whatever reason.

**Comment by GabePoel** [comment]
Fixed in new version. 🙂
