### ISSUE TITLE
QT6 support

### ISSUE THREAD

**Issue by KaspianDev** [GabePoel/KvLibadwaita#5]
Hey, is this theme getting qt6 support?

**Comment by inari-codes** [comment]
You need to compile Kvantum against Qt5 and Qt6 to have support for Qt6, this theme by itself can't

**Comment by KaspianDev** [comment]
> You need to compile Kvantum against Qt5 and Qt6 to have support for Qt6, this theme by itself can't

actually i have both kvantum qt6 and qt5 packages :/

looks like its a problem in app im using not the kvlibadwaita itself
