### ISSUE TITLE
Mind you sharing the window decoration?

### ISSUE THREAD

**Issue by juacq97** [GabePoel/KvLibadwaita#7]
Hi! This theme looks awesome. In the picture you're using an aurorae theme very similar to GNOME decorations. I can't find the theme on kde store, so can you share it? It'll complete the KNOME experience

**Comment by GabePoel** [comment]
There's actually a very good reason the screenshot's decorations look like GNOME ones. It was taken on GNOME (using [adw-gtk3](https://github.com/lassekongo83/adw-gtk3))! You could probably get similar decorations by using/modifying [colloid-kde](https://github.com/vinceliuice/Colloid-kde).
